version: '3.4'

services:

  identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "7580:80"
      - "7543:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  mssqldb:
    environment:
      SA_PASSWORD: "Devadmin321"
      ACCEPT_EULA: "Y"
    ports:
      - "5433:1433"
    volumes:
      - mssqlserver-data:/var/opt/mssql